shell.execute("wget https://raw.githubusercontent.com/alexandersokol/oc-home-apps/master/src/aspect/aspect.lua /home/aspect.lua")
shell.execute("wget https://raw.githubusercontent.com/alexandersokol/oc-home-apps/master/src/thaum_matrix/crafting_state.lua /home/crafting_state.lua")
shell.execute("wget https://raw.githubusercontent.com/alexandersokol/oc-home-apps/master/src/thaum_matrix/master.lua /home/master.lua")
shell.execute("wget https://raw.githubusercontent.com/alexandersokol/oc-home-apps/master/src/thaum_matrix/options.lua /home/options.lua")
shell.execute("wget https://raw.githubusercontent.com/alexandersokol/oc-home-apps/master/src/thaum_matrix/recipes.lua /home/recipes.lua")